name: Build + Publish

on:
    push:
        branches:
            - main
        tags:
            - 'v*'

permissions:
    contents: read
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - uses: actions/setup-node@v6
              with:
                  node-version: 25

            - run: npm ci

            - run: npm run test

            - run: npm run typecheck

            - run: npm run lint

            - run: npm run format:check

            - run: npm run build

    publish:
        needs: build
        runs-on: ubuntu-latest

        if: startsWith(github.ref, 'refs/tags/v')

        steps:
            - uses: actions/checkout@v6

            - uses: actions/setup-node@v6
              with:
                  node-version: 25
                  registry-url: https://registry.npmjs.org/

            - run: npm ci

            - run: npm run build

            # - run: npm publish --provenance --dry-run
